### PR TITLE
Batch tagging

### PR DESCRIPTION
**Pull request by gilesdring**
Added batch tagging

To apply this, run the `tags:batch` rake task.

This task takes arguments: the first is the input file, the second is the output file. These default to `./data/batch_tags.csv` and `./batch_tags.log.csv` respectively.

The output file is compatible with the input file (i.e. can be used as an input). It reports errors, so these can be progressively fixed. Cool, huh?

### CODE REVIEW

**Comment by Floppy** [comment]
We need to test this and merge it in. @pezholio, might you have time to have a look at it sometime?

**Comment by pezholio** [comment]
Aye, I'll take a peek now

**Comment by pezholio** [comment]
I've looked at this and it seems to work, but I do get a few errors. What problem is this solving?

**Comment by gilesdring** [comment]
It's retrospective re tagging old artefacts. I was given a CSV by Phil L with lists of tags. Some are out of date (tags don't exist, artefacts don't exist) or don't validate ('people' need 'teams').

Are the errors code or data? If code - oops - need fixing. I'd data (I.e. In output CSV) the task will not change the artefact but will report that the combo of artefact and tag set ain't valid. This is for Phil to resolve or ignore

**Comment by pezholio** [comment]
Ah, awesome. It's just data errors. Everything runs fine. What's the next step? Do we run it on live and give Phil the output?

**Comment by gilesdring** [comment]
Yep. That's the idea. I figured with a list that long, I'd better make sure I did what I could then provide the opportunity to refine and resolve if required... The output can be corrected and fed back in as an input...

**Comment by pezholio** [comment]
Cool, cool, cool. I shall merge in that case! :+1:

**Pull request merged**
